Added functions to take screenshot of bookmarks

diff --git a/bm b/bm
--- a/bm
+++ b/bm
@@ -17,10 +17,10 @@ config() {
 	fi
 
 	# _BM_BOOKMARK_FILE : Where is stored the bookmark file
-	export _BM_BOOKARK_FILE="${_BM_BOOKMARK_FILE:=${__w}bm.lnk}"
+	export _BM_BOOKMARK_FILE="${_BM_BOOKMARK_FILE:=${__w}bm.lnk}"
 
 	# _BM_BOOKMARK_BACKUP_FILE : Where is stored the backup of bookmark file
-	export _BM_BOOKARK_BACKUP_FILE="${_BM_BOOKMARK_BACKUP_FILE:=${__w}.bm.lnk.bck}"
+	export _BM_BOOKMARK_BACKUP_FILE="${_BM_BOOKMARK_BACKUP_FILE:=${__w}.bm.lnk.bck}"
 
 	# _BM_HTML_FILE : Location of generated HTML file
 	export _BM_HTML_FILE="${_BM_HTML_FILE:=${__w}bm.html}"
@@ -49,11 +49,14 @@ config() {
 	# _BM_GET_PAGE_TITLE : When adding a URL execute a curl command to get the <title> if none given
 	export _BM_GET_PAGE_TITLE=${_BM_GET_PAGE_TITLE:=true}
 
-	# _BM_GET_SCREENSHOT : When adding a URL try to take a screenshot in background
-	export _BM_GET_SCREENSHOT=${_BM_GET_SCREENSHOT:=true}
+	# _BM_SCREENSHOT_DIRECTORY : Where to store the screenshot taken
+	export _BM_SCREENSHOT_DIRECTORY="${_BM_SCREENSHOT_DIRECTORY:=${__w}/.bm.shots}"
 
-	# _BM_WAIT_SCREENSHOT : When taking a screenshot wait for the action to finish
-	export _BM_WAIT_SCREENSHOT=${_BM_WAIT_SCREENSHOT:=false}
+	# _BM_SCREENSHOT_GET : When adding a URL try to take a screenshot in background
+	export _BM_SCREENSHOT_GET=${_BM_SCREENSHOT_GET:=true}
+
+	# _BM_SCREENSHOT_WAIT : When taking a screenshot wait for the action to finish
+	export _BM_SCREENSHOT_WAIT=${_BM_SCREENSHOT_WAIT:=false}
 
 	# _BM_OPEN_FIRST : When using open, the first link found is open
 	#              Also work with the copy to clipboard function
@@ -74,17 +77,22 @@ config() {
 	export _BM_CMD_CAPTURE_CHECK=${_BM_CMD_CAPTURE_CHECK:=true}
 
 	# I suppose the uname command is available
+	# Please note, the PRE & POST capture command will not be analyzes nor verified.
 	if [ "$(uname -s)" = 'Linux' ]; then
 		export _BM_CMD_OPEN='xdg-open'
+		export _BM_CMD_PRE_CAPTURE=''
 		export _BM_CMD_CAPTURE='cutycapt'
-		export _BM_CMD_CAPTURE_ARGS='--url={URL} --output={FILE}.png'
+		export _BM_CMD_CAPTURE_ARGS='--url={URL} --out={FILE}'
+		export _BM_CMD_POST_CAPTURE=''
 		export _BM_CMD_MD5='md5sum'
 		export _BM_CMD_COPY='xsel'
 	else
 		# To keep commpatibility with the Mac (even i don't have any)
 		export _BM_CMD_OPEN='open'
+		export _BM_CMD_PRE_CAPTURE=''
 		export _BM_CMD_CAPTURE='webkit2png'
 		export _BM_CMD_CAPTURE_ARGS='-C -o {FILE}.png {URL}'
+		export _BM_CMD_POST_CAPTURE='cp -- "{FILE}-clipped.png" "{FILE}" ; rm -f -- {FILE}-{clipped,full,thumb}.png'
 		export _BM_CMD_MD5='md5'
 		export _BM_CMD_COPY='xsel'
 	fi
@@ -158,6 +166,7 @@ Usage: ${0} [modifier(s)] command [option(s)]
 					Default is FQDN without gTld (and www, and sheme)
 			-F		Force the bookmark to be created (even if duplicate
 					or invalid)
+			-p		Force the screenshot to be taken
 	
 	-l		List all URLs (default action, same thing as calling bm without args)
 
@@ -267,7 +276,7 @@ saveUrl() {
 	fi
 	local _sum="$(${_BM_CMD_MD5} <<< "${__url}")"
 	if [ ${_BM_DUPS_DETECT} = true ]; then
-		if [ ! -z "$(awk -F '|' '$1 ~ /'"${_sum%% *}"'/' "${_BM_BOOKMARK_FILE}")" ]; then
+		if [ ! -z "$(awk -F '|' '$0 !~ /^[ 	]*#/ && $1 ~ /'"${_sum%% *}"'/' "${_BM_BOOKMARK_FILE}")" ]; then
 			if [ ${__F:=0} -eq 0 ]; then
 				die "URL is already in the Bookmark file"
 			else
@@ -275,17 +284,23 @@ saveUrl() {
 			fi
 		fi
 	fi
+set -xv
 	if [ ${_BM_GET_PAGE_TITLE} = true -a -z "${__T:=}" ]; then
 		__T="$( curl -ks "${__url}" 2>&1 | sed '/<title>/I!d;/<\/title>/I!d;s;^[[:space:]]*<title>\([^<]*\)<.*;\1;i' )" &
 	fi
+set +xv
 	backupBm
+set -xv
 	wait
 	[[ -z "${__T:=}" ]] && __T="$(slug <<< "${__url}")"	# If no title => slug the url
+set +xv
 	[[ -z "${__t:=}" ]] && __t='default'			# Default tag is default
 	[[ -z "${__A:=}" ]] && __A="$(getAccelMax)"
 	[[ "${__A:0:1}" != ':' ]] && __A=":${__A}"		# If no accel => Add a number
 	echo "${_sum%% *}|${__A}|${__url}|${__T}|${__t}|$(date '+%FT%TZ')" >> "${_BM_BOOKMARK_FILE}" || die "Insert aborted into '${_BM_BOOKMARK_FILE}' !"
 	echo "${__url} inserted into '${_BM_BOOKMARK_FILE}'"
+	[[ ! -f "${_BM_SCREENSHOT_DIRECTORY}/${_sum%% *}.png" || ${__F:=0} -eq 1 ]] && { screenshot_take "${_BM_SCREENSHOT_DIRECTORY}/${_sum%% *}.png" "${__url}" & }
+	[[ ${_BM_SCREENSHOT_WAIT} = true ]] && wait
 	search_bookmarks "${__A}"
 }
 
@@ -315,7 +330,7 @@ readLines() {
 #
 
 list_bookmarks() {
-	awk '$0 !~ /^[       ]*#/' "${_BM_BOOKMARK_FILE}" | readLines
+	awk '$0 !~ /^[ 	]*#/' "${_BM_BOOKMARK_FILE}" | readLines
 }
 
 #
@@ -336,15 +351,12 @@ search() {
 		BEGIN {
 			if (Ign == 1) { s=tolower("'"${1:${_ss}}"'"); } else { s="'"${1:${_ss}}"'"; }
 		}
-		$0 !~ /^[       ]*#/ && (Ign == 0 && $'"${_s}"' ~ s) || (Ign ==1 && tolower($'"${_s}"') ~ s) {print $0;}
+		$0 !~ /^[ 	]*#/ && (Ign == 0 && $'"${_s}"' ~ s) || (Ign ==1 && tolower($'"${_s}"') ~ s) {print $0;}
 	' "${_BM_BOOKMARK_FILE}" 
 
 }
 search_bookmarks() {
-#set -xv
 	search "${@}" | readLines
-#	search "${@}" 
-#	readLines < <(search "${@}")
 }
 
 #
@@ -424,10 +436,10 @@ delete_bookmark() {
 #
 stats() {
 	readarray -t lines < "${_BM_BOOKMARK_FILE}"
-	#local lines=${#lines[@]}
 	echo "# of Bookmarks	:	${#lines[@]}"
-	echo "# of Duplicate	:	$(awk -F'|' '{print $1}' "${_BM_BOOKMARK_FILE}" |sort |uniq -d |wc -l)"
-	local tags="$(awk -F'|' '$0 !~ /^[       ]*#/ {print $5}' "${_BM_BOOKMARK_FILE}" | sed -e 's/\([[:space:]]*,[[:space:]]*\)/\n/g')"
+	echo "# of Duplicate	:	$(awk -F'|' '$0 !~ /^[	 ]*#/ {print $1}' "${_BM_BOOKMARK_FILE}" |sort |uniq -d |wc -l)"
+	echo "# of Pictures	:	$(ls -1 "${_BM_SCREENSHOT_DIRECTORY}"/* |wc -l)"
+	local tags="$(awk -F'|' '$0 !~ /^[ 	]*#/ {print $5}' "${_BM_BOOKMARK_FILE}" | sed -e 's/\([[:space:]]*,[[:space:]]*\)/\n/g')"
 
 	echo "# of tags	:	$( sort -u <<< "${tags,,}" |wc -l)"
 	echo "Top 14 tags used	:"
@@ -440,6 +452,9 @@ stats() {
 		done
 		echo ''
 	) | column -t -x -c 7
+	local orphaned="$( cd "${_BM_SCREENSHOT_DIRECTORY}" && for i in *; do [[ -z "$(sed -e '/'"${i%%.*}"'/!d' "${_BM_BOOKMARK_FILE}")" ]] && ((orph++)); done; echo "${orph:=0}" )"
+	local nopics="$( while read i; do [[ ! -f "${_BM_SCREENSHOT_DIRECTORY}/${i%%|*}.png" ]] && ((nopics++)); done <<< ${lines[@]}; echo "${nopics:=0}" )"
+	[[ ${orphaned:=0} -ne 0 || ${nopics:=0} -ne 0 ]] && echo -e "About pictures...\nOrphaned pictures	: ${orphaned}\nBookmark Without Pic	: ${nopics}"
 }
 
 #
@@ -447,7 +462,7 @@ stats() {
 #
 
 list_tags() {
-	local tags="$(awk -F'|' '$0 !~ /^[       ]*#/ {print $5}' "${_BM_BOOKMARK_FILE}" | sed -e 's/\([[:space:]]*,[[:space:]]*\)/\n/g')"
+	local tags="$(awk -F'|' '$0 !~ /^[ 	]*#/ {print $5}' "${_BM_BOOKMARK_FILE}" | sed -e 's/\([[:space:]]*,[[:space:]]*\)/\n/g')"
 	local nli=0
 	(
 		sort <<< "${tags,,}" | uniq -c | sort -nr | while read n t; do
@@ -544,6 +559,27 @@ urls() {
 # Generate bookmark screenshots
 #
 
+screenshot_take() {
+set -xv
+	if [ ${_BM_SCREENSHOT_GET} = true -o ${__p:=0} -eq 1 ]; then
+		[[ ! -d "${_BM_SCREENSHOT_DIRECTORY}" ]] && { mkdir -p "${_BM_SCREENSHOT_DIRECTORY}" || die "Can't create thumbnail directory." ; }
+		[[ ! -z "${_BM_CMD_PRE_CAPTURE}" ]] && { local _pre="${_BM_CMD_PRE_CAPTURE//\{FILE\}/${1}}"; _pre="${_pre//\{URL\}/${2}}"; ${_pre} ; }
+		local _cmd="${_BM_CMD_CAPTURE//\{FILE\}/${1}}"; _cmd="${_cmd//\{URL\}/${2}}";
+		local _args="${_BM_CMD_CAPTURE_ARGS//\{FILE\}/${1}}"; _args="${_args//\{URL\}/${2}}";
+		${_cmd} ${_args}
+		[[ ! -z "${_BM_CMD_POST_CAPTURE}" ]] && { local _post="${_BM_CMD_POST_CAPTURE//\{FILE\}/${1}}"; _post="${_post//\{URL\}/${2}}"; ${_post} ; }
+set +xv
+	fi
+set +xv
+}
+
+picturize() {
+	awk '$0 !~ /^[  ]*#/ {print $1,$3;}' "${_BM_BOOKMARK_FILE}" | while read m u; do
+		[[ ! -f "${_BM_SCREENSHOT_DIRECTORY}/${m}.png" || ${__F:=0} -eq 1 ]] && { screenshot_take "${_BM_SCREENSHOT_DIRECTORY}/${m}.png" "${u}" & }
+		[[ ${_BM_SCREENSHOT_WAIT} = true ]] && wait
+	done
+}
+
 create_bookmark_screenshots() {
   which webkit2png > /dev/null
 
@@ -572,6 +608,7 @@ create_bookmark_screenshots() {
   done
 
   rm -f out.png-{clipped,full,thumb}.png
+      mv out.png-clipped.png $path ; rm -f out.png-{clipped,full,thumb}.png
 }
 
 #
@@ -726,9 +763,9 @@ else
 # -g generate html file
 # -G use this file
 # -g -g generate 1 file per tags
-        # used      : Aa-bCcDd--F--gHh-i----Ll----Oo------SsTt--Vv-w--Y-------------
-        # available : --B-----Ee-fG---I-JjKk--MmNn--PpQqRr----Uu--W-Xx-yZz0123456789
-	while getopts ":a:A:b:c:d:o:s:t:T:w:x:CDFghHilLOSvVXY" option; do
+        # used      : Aa-bCcDd--F--gHh-i----Ll----Oo-p----SsTt--Vv-w--Y-------------
+        # available : --B-----Ee-fG---I-JjKk--MmNn--P-QqRr----Uu--W-Xx-yZz0123456789
+	while getopts ":a:A:b:c:d:o:s:t:T:w:x:CDFghHilLOpSvVXY" option; do
 		case ${option} in
 			a) __a=1; __url="${OPTARG}";;	# Add url to bookmark
 			A) __A="${OPTARG}";;	# AcceleratoR
@@ -745,6 +782,8 @@ else
 			L) __L=1;;		# List all tags
 			o) __o=1; __open="${OPTARG}";;	# Open
 			O) __O=1;;		# Open First
+			p) __p=1;;		# Take a screenshot
+			P) __P=1;;		# Take all screenshot
 			s) __s=1; __search="${OPTARG}";;	# Search
 			S) __S=1;;		# Print Statistics
 			t) __t="${OPTARG}";;	# tags for a URL
@@ -787,8 +826,8 @@ fi
 [[ ${#} -eq 0 && ${_BM_NO_ARGS_FORCE_HELP:=0} -eq 0 ]] && __l=1
 
 # Only one action at a time
-if [ $(( ${__a:=0} + ${__C:=0} + ${__d:=0} + ${__g:=0} + ${__l:=0} + ${__L:=0} + ${__o:=0} + ${__x:=0} + ${__s:=0} + ${__S:=0} )) -gt 1 ]; then
-        echo "You have to choose between -a, -C, -d, -g, -l, -L, -o, -s, -S, -x" >&2
+if [ $(( ${__a:=0} + ${__C:=0} + ${__d:=0} + ${__g:=0} + ${__l:=0} + ${__L:=0} + ${__o:=0} + ${__P:=0} + ${__s:=0} + ${__S:=0} + ${__x:=0} )) -gt 1 ]; then
+        echo "You have to choose between -a, -C, -d, -g, -l, -L, -o, -P, -s, -S, -x" >&2
         echo "Use -h for help" >&2
 	exit 0
 fi
@@ -800,13 +839,14 @@ fi
 
 # Executing actions
 [[ ${__a} -eq 1 ]] && { saveUrl ;  exit ; }
+[[ ${__C} -eq 1 ]] && { defineColors 1 ; exit ; }
 [[ ${__d} -eq 1 ]] && { delete_bookmark "${__del}";  exit ; }
-[[ ${__s} -eq 1 ]] && { search_bookmarks "${__search}" ; exit; }
 [[ ${__l} -eq 1 ]] && { search ; exit; }
 [[ ${__L} -eq 1 ]] && { list_tags ; exit; }
 [[ ${__o} -eq 1 ]] && { open_bookmark "${__open}" ; exit; }
+[[ ${__P} -eq 1 ]] && { picturize ; exit; }
 [[ ${__x} -eq 1 ]] && { copy_bookmark "${__copy}" ; exit; }
+[[ ${__s} -eq 1 ]] && { search_bookmarks "${__search}" ; exit; }
 [[ ${__S} -eq 1 ]] && { stats ; exit; }
-[[ ${__C:=0} -eq 1 ]] && { defineColors 1 ; exit ; }
 
 # $Format:%cn @ %cD$ : $Id$
