Changing fields order in the bookmarks file. Adding a migration tool from tj/bm to Flyounet/bm v0.6.0

diff --git a/bm b/bm
--- a/bm
+++ b/bm
@@ -289,7 +289,7 @@ getAccelMax() {
 #	' "${_BM_BOOKMARK_FILE}"
 	while read a; do
 		(( ${a:=0} >= ${_max:=0} )) && (( _max=${a}+1 ))
-	done <<< "$( awk -F'|' '$0 !~ /^[ 	]*#/ && $2 ~ /^[:space:]*:[:space:]*[0-9]+[:space:]*$/ { sub(/:+/, "", $2); print $2; }' "${_BM_BOOKMARK_FILE}")"
+	done <<< "$( awk -F'|' '$0 !~ /^[ 	]*#/ && $3 ~ /^[:space:]*:[:space:]*[0-9]+[:space:]*$/ { sub(/:+/, "", $3); print $3; }' "${_BM_BOOKMARK_FILE}")"
 	echo -n "${_max}"
 }
 
@@ -328,7 +328,7 @@ saveUrl() {
 	[[ -z "${__t:=}" ]] && __t='default'			# Default tag is default
 	[[ -z "${__A:=}" ]] && __A="$(getAccelMax)"
 	[[ "${__A:0:1}" != ':' ]] && __A=":${__A}"		# If no accel => Add a number
-	echo "${_sum%% *}|${__A}|${__url}|${__T}|${__t}|$(date '+%FT%TZ')" >> "${_BM_BOOKMARK_FILE}" || die "Insert aborted into '${_BM_BOOKMARK_FILE}' !"
+	echo "${_sum%% *}|$(date '+%FT%TZ')|${__A}|${__url}|${__T}|${__t}" >> "${_BM_BOOKMARK_FILE}" || die "Insert aborted into '${_BM_BOOKMARK_FILE}' !"
 	echo "${__url} inserted into '${_BM_BOOKMARK_FILE}'"
 	[[ ! -f "${_BM_SCREENSHOT_DIRECTORY}/${_sum%% *}.png" || ${__F:=0} -eq 1 ]] && { screenshot_take "${_BM_SCREENSHOT_DIRECTORY}/${_sum%% *}.png" "${__url}" & }
 	[[ ${_BM_SCREENSHOT_WAIT} = true ]] && wait
@@ -341,7 +341,7 @@ saveUrl() {
 
 readLines() {
 	IFS='|'
-	while read m a u T t d; do
+	while read m d a u T t; do
 		_line="${_BM_PRINT_LINE}"
 		[[ ${__z:=0} -eq 1 ]] && _line="${_BM_PRINT_LINE_ALTERNATIVE}"
 		_line="${_line//BM_MD5/$m}"
@@ -375,10 +375,10 @@ search() {
 	local _s=''
 	[[ -z "${1:-}" ]] && list_bookmarks && return
 	case "${1:0:1}" in
-		:) _s=2; _ss=0 ;; # Accelerator
-		+) _s=5; _ss=1 ;; # Tags
+		:) _s=3; _ss=0 ;; # Accelerator
+		+) _s=6; _ss=1 ;; # Tags
 		=) _s=1; _ss=1 ;; # MD5 part
-		/) _s=3; _ss=1 ;; # URL part
+		/) _s=4; _ss=1 ;; # URL part
 		*) _s=0; _ss=0 ;; # full text search
 	esac
 	[[ ${_BM_SEARCH_IGNORECASE} = true || ${__i:=0} -eq 1 ]] && local _ign=1
@@ -432,9 +432,9 @@ open_bookmark() {
 	while read _nl; do
 		readLines <<< "${_nl}"
 		if [ ${_BM_OPEN_ALL} = true -o ${__Y:=0} -eq 1 ]; then
-			_all="$(awk -F'|' '{print $3}' <<< "${_nl}") ${_all}"
+			_all="$(awk -F'|' '{print $4}' <<< "${_nl}") ${_all}"
 		else
-			"${_BM_CMD_OPEN}" "$(awk -F'|' '{print $3}' <<< "${_nl}")"
+			"${_BM_CMD_OPEN}" "$(awk -F'|' '{print $4}' <<< "${_nl}")"
 			[[ ${_BM_OPEN_FIRST} = true || ${__O:=0} -eq 1 ]] && exit 0
 		fi
 	done <<< "$(echo -e "${_lines}")"
@@ -453,10 +453,10 @@ copy_bookmark() {
 	while read _nl; do
 		readLines <<< "${_nl}"
 		if [ ${_BM_OPEN_ALL} = true -o ${__Y:=0} -eq 1 ]; then
-			_all="$(awk -F'|' '{print $3}' <<< "${_nl}") ${_all}"
+			_all="$(awk -F'|' '{print $4}' <<< "${_nl}") ${_all}"
 		else
-			awk -F'|' '{print $3}' <<< "${_nl}" | "${_BM_CMD_COPY}"
-			awk -F'|' '{print $3}' <<< "${_nl}" | "${_BM_CMD_COPY}" -b
+			awk -F'|' '{print $4}' <<< "${_nl}" | "${_BM_CMD_COPY}"
+			awk -F'|' '{print $4}' <<< "${_nl}" | "${_BM_CMD_COPY}" -b
 			[[ ${_BM_OPEN_FIRST} = true || ${__X:=0} -eq 1 ]] && exit 0
 		fi
 	done <<< "$(echo -e "${_lines}")"
@@ -508,7 +508,7 @@ stats() {
 	readarray -t lines < "${_BM_BOOKMARK_FILE}"
 	echo "# of Bookmarks		: ${#lines[@]}"
 	echo "# of Duplicate		: $(awk -F'|' '$0 !~ /^[	 ]*#/ {print $1}' "${_BM_BOOKMARK_FILE}" |sort |uniq -d |wc -l)"
-	local tags="$(awk -F'|' '$0 !~ /^[ 	]*#/ {print $5}' "${_BM_BOOKMARK_FILE}" | sed -e 's/\([[:space:]]*,[[:space:]]*\)/\n/g')"
+	local tags="$(awk -F'|' '$0 !~ /^[ 	]*#/ {print $6}' "${_BM_BOOKMARK_FILE}" | sed -e 's/\([[:space:]]*,[[:space:]]*\)/\n/g')"
 
 	echo "# of tags		: $( sort -u <<< "${tags,,}" |wc -l)"
 	echo "Top 14 tags used	:"
@@ -527,7 +527,7 @@ stats() {
 	local nopics="$( while read i; do [[ ! -f "${_BM_SCREENSHOT_DIRECTORY}/${i%%|*}.png" ]] && ((nopics++)); done <<< ${lines[@]}; echo "${nopics:=0}" )"
 	echo "Bookmark Without Pic	: ${nopics}"
 	echo "Orphaned pictures	: ${orphaned}"
-	[[ ${__p:=0} -eq 1 ]] && { echo -e "\n=====   Orphaned   ====="; echo "List of orphaned pictures :"; cd "${_BM_SCREENSHOT_DIRECTORY}" && for i in *; do [[ -z "$(sed -e '/'"${i%%.*}"'/!d' "${_BM_BOOKMARK_FILE}")" ]] && echo " - ${_BM_SCREENSHOT_DIRECTORY}/${i} [Trashed URL should be: $(awk -F'|' 'BEGIN{l="Unknown"} ($1 ~ /'"${i%%.*}"'/) {l=$3;} END {print l}' "${_BM_DELETE_FILE}")]"; done; };
+	[[ ${__p:=0} -eq 1 ]] && { echo -e "\n=====   Orphaned   ====="; echo "List of orphaned pictures :"; cd "${_BM_SCREENSHOT_DIRECTORY}" && for i in *; do [[ -z "$(sed -e '/'"${i%%.*}"'/!d' "${_BM_BOOKMARK_FILE}")" ]] && echo " - ${_BM_SCREENSHOT_DIRECTORY}/${i} [Trashed URL should be: $(awk -F'|' 'BEGIN{l="Unknown"} ($1 ~ /'"${i%%.*}"'/) {l=$4;} END {print l}' "${_BM_DELETE_FILE}")]"; done; };
 }
 
 #
@@ -535,7 +535,7 @@ stats() {
 #
 
 list_tags() {
-	local tags="$(awk -F'|' '$0 !~ /^[ 	]*#/ {print $5}' "${_BM_BOOKMARK_FILE}" | sed -e 's/\([[:space:]]*,[[:space:]]*\)/\n/g')"
+	local tags="$(awk -F'|' '$0 !~ /^[ 	]*#/ {print $6}' "${_BM_BOOKMARK_FILE}" | sed -e 's/\([[:space:]]*,[[:space:]]*\)/\n/g')"
 	local nli=0
 	(
 		sort <<< "${tags,,}" | uniq -c | sort -nr | while read n t; do
@@ -639,7 +639,7 @@ screenshot_take() {
 
 picturize() {
 	if [ -z "${1:-}" ]; then
-		awk -F'|' '$0 !~ /^[  ]*#/ {print $1,$3;}' "${_BM_BOOKMARK_FILE}" | while read m u; do
+		awk -F'|' '$0 !~ /^[  ]*#/ {print $1,$4;}' "${_BM_BOOKMARK_FILE}" | while read m u; do
 			[[ ! -f "${_BM_SCREENSHOT_DIRECTORY}/${m}.png" || ${__F:=0} -eq 1 ]] && { screenshot_take "${_BM_SCREENSHOT_DIRECTORY}/${m}.png" "${u}" & }
 			[[ ${_BM_SCREENSHOT_WAIT} = true ]] && wait
 		done
@@ -672,7 +672,7 @@ bookmark_generator() {
 	style >> "${1:-${_BM_HTML_FILE}}"
 	echo "</head><body>" >> "${1:-${_BM_HTML_FILE}}"
 #	search "${2:-}" | while IFS='|' read m a u T t d; do
-	awk '$0 !~ /^[  ]*#/' "${_BM_BOOKMARK_FILE}" | while IFS='|' read m a u T t d; do
+	awk '$0 !~ /^[  ]*#/' "${_BM_BOOKMARK_FILE}" | while IFS='|' read m d a u T t; do
 	echo "	<div class=bm>
 		<a href='${u}'><img src='${_BM_SCREENSHOT_DIRECTORY}/${m}.png' alt='${u}' /></a>
 		<p>${T}<br/><a href='${_BM_SCREENSHOT_DIRECTORY}/${m}.png'>View image</a></p>
@@ -864,8 +864,8 @@ config "${__c}"
 # If no bookmark file exist, create one if allowed
 if [ ! -f "${_BM_BOOKMARK_FILE}" -a ${_BM_CREATE_BOOKMARK_FILE} = true ]; then
 	# Remember fields : 1=md5, 2=accel, 3=url, 4=title, 5=tags, 6=date of bookmark
-	echo "bd8b3eff7fa82a0382a3e7576c5363b6|:bm|https://github.com/Flyounet/bm/|bm a cool enhanced bookmark tool for your console|default,shell|$(date '+%FT%TZ')" >> "${_BM_BOOKMARK_FILE}"
-	echo "2981b5cae113491ddb18e0d51454f0d9|:bmtj|https://github.com/tj/bm/|The original bm : a cool bookmark tool for your console|default,shell|$(date '+%FT%TZ')" >> "${_BM_BOOKMARK_FILE}"
+	echo "bd8b3eff7fa82a0382a3e7576c5363b6|$(date '+%FT%TZ')|:bm|https://github.com/Flyounet/bm/|bm a cool enhanced bookmark tool for your console|default,shell" >> "${_BM_BOOKMARK_FILE}"
+	echo "2981b5cae113491ddb18e0d51454f0d9|$(date '+%FT%TZ')|:bmtj|https://github.com/tj/bm/|The original bm : a cool bookmark tool for your console|default,shell" >> "${_BM_BOOKMARK_FILE}"
 fi
 
 # Starting to work with args. If none probably list...
